services:
  - type: web
    name: ecovalue-india-api
    region: singapore
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: GROQ_API_KEY
        sync: false          # Get free key at https://console.groq.com
      - key: DATABASE_URL
        sync: false          # leave blank for SQLite, or add Postgres URL
    disk:
      name: ecovalue-db
      mountPath: /data
      sizeGB: 1
